select * from mytable;

alter table mytable drop column frequency_of_purchase_days;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue from mytable group by gender;

 
-- Q3. Which are the top 5 products with the highest average review rating?
select  item_purchased,round(avg (review_rating),1) as avg_rating from mytable group by item_purchased order by avg_rating desc limit 5;      

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

          -- select distinct shipping_type from mytable group by shipping_type;
		  -- select  shipping_type,avg(previous_purchases) from mytable group by shipping_type;
select  shipping_type,round(avg(purchase_amount),1) as purchase_amount from mytable where shipping_type  in( 'Express', 'Standard') group by shipping_type ;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.



-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select customer_id,previous_purchases,
case
 when previous_purchases = 1 then 'new'
 when previous_purchases between 2 and 10 then 'returning'
 else 'loyal'
 end as customers from mytable
)
  select customers count(*) as no_of_customers;

-- Q8. What are the top 3 most purchased products within each category?
select * from mytable;                                                                                                               #pending
select  category,item_purchased,sum(purchase_amount) as top from mytable group by category order by top desc limit 3 ;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


-- Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue_contribution_age from mytable group by age_group; 